### ISSUE TITLE
Problems encountered during testing

### ISSUE THREAD

**Issue by 123456789live** [mumianyuxin/M3DSSD#10]
Hello, author, I have a question. Among the evaluation results obtained from the training, there are two indicators of the car: AP@R11 and AP@R40. Are these two results on the val datasets? Or AP@R40 is the result on the testing datasets?
作者您好，我有个问题。在训练得到的评估结果中，有汽车在AP@R11和AP@R40两种指标，这两种都是在验证集上的结果吗，还是AP@R40是测试集上的结果 ?
bbox AP:93.4128, 86.0374, 76.3270
bev  AP:28.6008, 24.1458, 19.8311
3d   AP:23.5013, 18.5377, 16.8939
aos  AP:93.18, 85.31, 75.28
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:94.4730, 89.1243, 75.0301
bev  AP:25.3284, 19.6154, 15.5039
3d   AP:17.6740, 13.5385, 10.9201
aos  AP:94.25, 88.29, 74.02
Pedestrian AP@0.50, 0.50, 0.50:
bbox AP:72.4768, 64.8912, 56.7276
bev  AP:8.2554, 6.1055, 6.1303
3d   AP:7.4127, 5.7886, 5.7870
aos  AP:56.16, 48.96, 42.46
Pedestrian AP_R40@0.50, 0.50, 0.50:
bbox AP:73.0240, 62.6571, 53.7581
bev  AP:6.3362, 5.0528, 4.4319
3d   AP:5.5379, 4.2182, 3.5477
aos  AP:56.40, 47.08, 40.11
Cyclist AP@0.50, 0.50, 0.50:
bbox AP:71.7324, 55.8072, 48.8942
bev  AP:7.4572, 5.5556, 5.4545
3d   AP:6.1668, 5.3124, 5.3270
aos  AP:62.99, 47.76, 42.04
Cyclist AP_R40@0.50, 0.50, 0.50:
bbox AP:70.4419, 52.3072, 50.2627
bev  AP:3.8131, 2.2562, 1.9963
3d   AP:2.7601, 1.5694, 1.5516
aos  AP:61.29, 44.23, 42.05

Second question:I load the conf file and weights from the results of the training into the test file：
conf_path = '/ conf_path data01 / zq/M3DSSD - master/output/base / 20211215 _161854_14. 29574471493946 / kitti_3d_base. Conf'
weights_path = '/ weights_path data01 / zq/M3DSSD - master/output/base / 20211215 _161854_14. 29574471493946 / weights/model_dla102_best_pkl'
When I run Python scripts/test_rpn_3d.py ,The following error has occurred. What is the problem?

(zq5) omnisky@node01:/data01/zq/M3DSSD-master$ CUDA_VISIBLE_DEVICES=5 python3 scripts/test_rpn_3d.py
Traceback (most recent call last):
File "scripts/test_rpn_3d.py", line 17, in &lt; module&gt;
From lib.dataloader import Kitti_Dataset_torch, Kitti_Dataset_dali
ImportError: cannot import name 'Kitti_Dataset_dali'

**Comment by alfinnurhalim** [comment]
by any chance, have you solved this issue?

**Comment by 123456789live** [comment]
> by any chance, have you solved this issue?

Not yet. Can you solve this problem?

**Comment by alfinnurhalim** [comment]
> > by any chance, have you solved this issue?
> 
> Not yet. Can you solve this problem?

yes. if you look `train_rpn_3d.py` they simply comment out `Kitti_Dataset_dali`. I think they don't use it anymore.

but then raise a new problem as mentioned here [#4](https://github.com/mumianyuxin/M3DSSD/issues/4#issue-1005214212). I haven't solve the problem yet

**Comment by 123456789live** [comment]
> > > by any chance, have you solved this issue?
> > 
> > 
> > Not yet. Can you solve this problem?
> 
> yes. if you look `train_rpn_3d.py` they simply comment out `Kitti_Dataset_dali`. I think they don't use it anymore.
> 
> but then raise a new problem as mentioned here [#4](https://github.com/mumianyuxin/M3DSSD/issues/4#issue-1005214212). I haven't solve the problem yet

A new problem arises when I comment out Kitti_Dataset_dali
Traceback (most recent call last):
File "scripts/test_rpn_3d.py", line 60, in &lt; module&gt;
Test_kitti_3d (dataset_test, net, conf, results_path, paths.data, use_log=False,val_train=val_train)
TypeError: test_kitti_3d() got an unexpected keyword argument 'val_train'
But I don't have a problem with #4
