### ISSUE TITLE
promeble in training

### ISSUE THREAD

**Issue by libingDY** [mumianyuxin/M3DSSD#6]
![2021-11-01 17-16-40 的屏幕截图](https://user-images.githubusercontent.com/73631342/139650421-b5295ecd-35ec-41bd-bc24-bbc37f01a6f1.png)
when i use "python scripts/train_rpn_3d.py --config=kitti_3d_base --exp_name base"to train the modle in kitti data ,after taining 10 epoch ,The following problems occurred.
''Traceback (most recent call last):
  File "scripts/train_rpn_3d.py", line 323, in <module>
    main(args)
  File "scripts/train_rpn_3d.py", line 288, in main
    iou_3d = test_kitti_3d(dataset_val, rpn_net, conf, results_path, paths.data, writer=writer)
  File "/home/libing/newstorage/3Dobjectdetector/M3DSSD/lib/rpn_util.py", line 1884, in test_kitti_3d
    easy = res_stats['{}_{}_easy'.format(lbl, item)]
KeyError: 'Car_aos_easy'
''
this is why? thank for you!

**Comment by FangJingYunner** [comment]
@libingDY Hi,do you know where to download kitti_split1 ?
